# fly.toml
app = "whatsapp-bot-seunome" # Use o nome que apareceu na interface

primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false  # Impede que o app durma
  auto_start_machines = true

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "whatsapp_data"
  destination = "/data"

[env]
  NODE_ENV = "production"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"