services:
  - type: web
    name: whatsapp-bot
    env: node
    buildCommand: npm install && npm run render-postbuild
    startCommand: npm start
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-121.0.6167.85/chrome-linux64/chrome